### ISSUE TITLE
Wget don't work anymore 

### ISSUE THREAD

**Issue by hinteor** [diejuse/chroot_Maemo-leste_on_Android#1]
Device model - redmi note 8t (custom firmware Pixel experience)
when trying to download the image using wget, I got the following errors: 
`wget: note: TLS certificate validation not implemented
 wget: TLS error from peer (alert code 80): 80
 wget: error getting response: Connection reset by peer.`
the latest version of magisk is being used and the version of busybox you recommend is installed.

**Comment by diejuse** [comment]
You don't really need "wget". You can skip that step by downloading the image yourself from any browser, putting the address: https://maedevu.maemo.org/images/arm64-generic/20200114/maemo-leste-1.0-arm64-raspi3-20200114.tar.gz

**Comment by diejuse** [comment]
Busybox magisk install is just not needed. Steps to install fixed.
